spring:
 profiles:
  active:
  - dev

---
server:
  port: 7801
spring:
 profiles: dev
 datasource:
     type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
     driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
     url: jdbc:mysql://localhost:3306/mldn8001           # 数据库连接地址
     username: root                                  # 数据库用户名
     password: root                                  # 数据库连接密码
     dbcp2:                                          # 进行数据库连接池的配置
       min-idle: 5                                   # 数据库连接池的最小维持连接数
       initial-size: 5                               # 初始化提供的连接数
       max-total: 5                                  # 最大的连接数
       # 等待连接获取的最大超时时间
       max-wait-millis: 200
 application:
  name: microcloud-config-dept-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: config-dept-client-7801.com
    prefer-ip-address: true

    ## 以下两项配置不建议自定义配置
    # 如果从上一次心跳到现在超过了5秒的间隔，还没有心跳的话，就认为当前服务已宕掉（默认是90秒）
#    lease-expiration-duration-in-seconds: 5
    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2
---
server:
  port: 7802
spring:
 profiles: beta
 datasource:
     type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
     driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
     url: jdbc:mysql://localhost:3306/mldn8002           # 数据库连接地址
     username: root                                  # 数据库用户名
     password: root                                  # 数据库连接密码
     dbcp2:                                          # 进行数据库连接池的配置
       min-idle: 5                                   # 数据库连接池的最小维持连接数
       initial-size: 5                               # 初始化提供的连接数
       max-total: 5                                  # 最大的连接数
       # 等待连接获取的最大超时时间
       max-wait-millis: 200
 application:
  name: microcloud-config-dept-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: config-dept-client-7802.com
    prefer-ip-address: true
---
server:
  port: 7803
spring:
 profiles: prod
 datasource:
     type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
     driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
     url: jdbc:mysql://localhost:3306/mldn8003           # 数据库连接地址
     username: root                                  # 数据库用户名
     password: root                                  # 数据库连接密码
     dbcp2:                                          # 进行数据库连接池的配置
       min-idle: 5                                   # 数据库连接池的最小维持连接数
       initial-size: 5                               # 初始化提供的连接数
       max-total: 5                                  # 最大的连接数
       # 等待连接获取的最大超时时间
       max-wait-millis: 200
 application:
  name: microcloud-config-dept-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: config-dept-client-7803.com
    prefer-ip-address: true