spring:
 profiles:
  active:
  - dev

---
server:
  port: 7701
spring:
 profiles: dev
 application:
  name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: config-client-7701.com
    prefer-ip-address: true

    ## 以下两项配置不建议自定义配置
    # 如果从上一次心跳到现在超过了5秒的间隔，还没有心跳的话，就认为当前服务已宕掉（默认是90秒）
#    lease-expiration-duration-in-seconds: 5
    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2
---
server:
  port: 7702
spring:
 profiles: beta
 application:
  name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: config-client-7702.com
    prefer-ip-address: true
---
server:
  port: 7703
spring:
 profiles: prod
 application:
  name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: config-client-7703.com
    prefer-ip-address: true